// Industry benchmark data for local businesses
// Sources: BrightLocal, Podium, ReviewTrackers industry averages

export const INDUSTRIES = [
  'Restaurant',
  'Dentist',
  'Plumber',
  'Salon / Barbershop',
  'Auto Repair',
  'Lawyer',
  'HVAC',
  'Landscaper',
  'Electrician',
  'Roofer',
  'Real Estate Agent',
  'Accountant / CPA',
  'Veterinarian',
  'Gym / Fitness',
  'Retail Store',
  'Chiropractor',
  'Cleaning Service',
  'Photographer',
  'Cafe / Coffee Shop',
  'Hotel / B&B',
  'Pet Groomer',
  'Daycare / Preschool',
  'Florist',
  'Pest Control',
]

// Benchmarks per industry: what "competitive" looks like
// reviewCount: number where you're competitive
// reviewCountStrong: number where you're a leader
// rating: competitive average rating
// ratingStrong: leader-level rating
export const BENCHMARKS = {
  'Restaurant': {
    reviewCount: 100,
    reviewCountStrong: 300,
    rating: 4.2,
    ratingStrong: 4.5,
    gbpPhotos: 30,
    gbpPhotosStrong: 75,
    label: 'Restaurant',
  },
  'Dentist': {
    reviewCount: 50,
    reviewCountStrong: 150,
    rating: 4.6,
    ratingStrong: 4.8,
    gbpPhotos: 15,
    gbpPhotosStrong: 40,
    label: 'Dental Practice',
  },
  'Plumber': {
    reviewCount: 30,
    reviewCountStrong: 100,
    rating: 4.4,
    ratingStrong: 4.7,
    gbpPhotos: 10,
    gbpPhotosStrong: 30,
    label: 'Plumbing Business',
  },
  'Salon / Barbershop': {
    reviewCount: 40,
    reviewCountStrong: 120,
    rating: 4.5,
    ratingStrong: 4.8,
    gbpPhotos: 20,
    gbpPhotosStrong: 50,
    label: 'Salon / Barbershop',
  },
  'Auto Repair': {
    reviewCount: 40,
    reviewCountStrong: 120,
    rating: 4.3,
    ratingStrong: 4.6,
    gbpPhotos: 15,
    gbpPhotosStrong: 40,
    label: 'Auto Repair Shop',
  },
  'Lawyer': {
    reviewCount: 20,
    reviewCountStrong: 60,
    rating: 4.7,
    ratingStrong: 4.9,
    gbpPhotos: 10,
    gbpPhotosStrong: 25,
    label: 'Law Firm',
  },
  'HVAC': {
    reviewCount: 30,
    reviewCountStrong: 100,
    rating: 4.4,
    ratingStrong: 4.7,
    gbpPhotos: 10,
    gbpPhotosStrong: 30,
    label: 'HVAC Company',
  },
  'Landscaper': {
    reviewCount: 20,
    reviewCountStrong: 75,
    rating: 4.5,
    ratingStrong: 4.8,
    gbpPhotos: 15,
    gbpPhotosStrong: 40,
    label: 'Landscaping Business',
  },
  'Electrician': {
    reviewCount: 25,
    reviewCountStrong: 80,
    rating: 4.5,
    ratingStrong: 4.8,
    gbpPhotos: 10,
    gbpPhotosStrong: 25,
    label: 'Electrical Contractor',
  },
  'Roofer': {
    reviewCount: 25,
    reviewCountStrong: 75,
    rating: 4.4,
    ratingStrong: 4.7,
    gbpPhotos: 15,
    gbpPhotosStrong: 40,
    label: 'Roofing Company',
  },
  'Real Estate Agent': {
    reviewCount: 15,
    reviewCountStrong: 50,
    rating: 4.7,
    ratingStrong: 4.9,
    gbpPhotos: 10,
    gbpPhotosStrong: 30,
    label: 'Real Estate Agent',
  },
  'Accountant / CPA': {
    reviewCount: 15,
    reviewCountStrong: 40,
    rating: 4.7,
    ratingStrong: 4.9,
    gbpPhotos: 8,
    gbpPhotosStrong: 20,
    label: 'Accounting Firm',
  },
  'Veterinarian': {
    reviewCount: 50,
    reviewCountStrong: 150,
    rating: 4.5,
    ratingStrong: 4.8,
    gbpPhotos: 20,
    gbpPhotosStrong: 50,
    label: 'Veterinary Clinic',
  },
  'Gym / Fitness': {
    reviewCount: 40,
    reviewCountStrong: 120,
    rating: 4.3,
    ratingStrong: 4.6,
    gbpPhotos: 20,
    gbpPhotosStrong: 50,
    label: 'Gym / Fitness Center',
  },
  'Retail Store': {
    reviewCount: 30,
    reviewCountStrong: 100,
    rating: 4.3,
    ratingStrong: 4.6,
    gbpPhotos: 15,
    gbpPhotosStrong: 40,
    label: 'Retail Store',
  },
  'Chiropractor': {
    reviewCount: 30,
    reviewCountStrong: 100,
    rating: 4.7,
    ratingStrong: 4.9,
    gbpPhotos: 10,
    gbpPhotosStrong: 30,
    label: 'Chiropractic Practice',
  },
  'Cleaning Service': {
    reviewCount: 25,
    reviewCountStrong: 80,
    rating: 4.5,
    ratingStrong: 4.8,
    gbpPhotos: 10,
    gbpPhotosStrong: 25,
    label: 'Cleaning Service',
  },
  'Photographer': {
    reviewCount: 15,
    reviewCountStrong: 50,
    rating: 4.8,
    ratingStrong: 5.0,
    gbpPhotos: 20,
    gbpPhotosStrong: 60,
    label: 'Photography Business',
  },
  'Cafe / Coffee Shop': {
    reviewCount: 60,
    reviewCountStrong: 200,
    rating: 4.3,
    ratingStrong: 4.6,
    gbpPhotos: 25,
    gbpPhotosStrong: 60,
    label: 'Cafe / Coffee Shop',
  },
  'Hotel / B&B': {
    reviewCount: 80,
    reviewCountStrong: 250,
    rating: 4.2,
    ratingStrong: 4.5,
    gbpPhotos: 30,
    gbpPhotosStrong: 80,
    label: 'Hotel / B&B',
  },
  'Pet Groomer': {
    reviewCount: 25,
    reviewCountStrong: 80,
    rating: 4.6,
    ratingStrong: 4.9,
    gbpPhotos: 15,
    gbpPhotosStrong: 40,
    label: 'Pet Grooming',
  },
  'Daycare / Preschool': {
    reviewCount: 20,
    reviewCountStrong: 60,
    rating: 4.5,
    ratingStrong: 4.8,
    gbpPhotos: 15,
    gbpPhotosStrong: 40,
    label: 'Daycare / Preschool',
  },
  'Florist': {
    reviewCount: 20,
    reviewCountStrong: 60,
    rating: 4.5,
    ratingStrong: 4.8,
    gbpPhotos: 20,
    gbpPhotosStrong: 50,
    label: 'Florist',
  },
  'Pest Control': {
    reviewCount: 25,
    reviewCountStrong: 80,
    rating: 4.5,
    ratingStrong: 4.8,
    gbpPhotos: 8,
    gbpPhotosStrong: 20,
    label: 'Pest Control Company',
  },
}

// Tooltips explaining where to find each metric
export const FIELD_TOOLTIPS = {
  googleReviewCount: 'Search for this business on Google Maps. The review count appears next to the star rating.',
  googleRating: 'The star rating shown on Google Maps, from 1.0 to 5.0.',
  respondsToReviews: 'Scroll through their Google reviews. Look for "Response from the owner" replies.',
  gbpPhotoCount: 'On their Google Business Profile, click "Photos" to see the total count.',
  gbpPostsRecent: 'On their GBP listing, scroll down to look for recent "Updates" or posts.',
  primaryCategory: 'Shown on their Google Business Profile, just below the business name.',
  hasWebsite: 'Check if they have a website linked on their Google Business Profile.',
  hasHttps: 'Visit their website. Look for the padlock icon in the browser address bar.',
  onYelp: 'Search for the business on yelp.com.',
  yelpRating: 'The star rating shown on their Yelp listing.',
  yelpReviewCount: 'The review count next to the star rating on Yelp.',
  onFacebook: 'Search for the business on Facebook.',
  facebookRating: 'The rating shown on their Facebook business page (if ratings are enabled).',
  facebookReviewCount: 'The number of reviews/recommendations on their Facebook page.',
  socialMediaPresence: 'Check if they have active profiles on Instagram, Facebook, X/Twitter, TikTok, YouTube, etc.',
  yearsInBusiness: 'Often listed on their website "About" page, or check their GBP listing for the opening date.',
  servicesListed: 'Count the distinct services or specialties listed on their website or GBP.',
  onlineBooking: 'Check their website for an online appointment/booking feature (Calendly, booking page, etc.).',
  teamPhotos: 'Look for an "About Us" or "Meet the Team" page with staff photos on their website.',
}

// Default empty business form
export const EMPTY_BUSINESS = {
  name: '',
  googleReviewCount: '',
  googleRating: '',
  respondsToReviews: '',
  gbpPhotoCount: '',
  gbpPostsRecent: '',
  primaryCategory: '',
  hasWebsite: '',
  hasHttps: '',
  onYelp: '',
  yelpRating: '',
  yelpReviewCount: '',
  onFacebook: '',
  facebookRating: '',
  facebookReviewCount: '',
  socialMediaPresence: '',
  yearsInBusiness: '',
  servicesListed: '',
  onlineBooking: '',
  teamPhotos: '',
}
